### ISSUE TITLE
bug: can't log in or sign up

### ISSUE THREAD

**Issue by RangePup** [Supamiu/ffxiv-teamcraft#192]
I tried to initially log in using my Google account. After having to turn my pop up blocker off, it finally gave me the window to sign in, and then told me invalid credentials. I tried going over to the Register tab, and tried putting in an email and password, clicked Submit and nothing seemed to happen. I tried to select the Google account option again, and was then greeted with "account already in use" so I went back to the log in option and tried again. It continued to say "Invalid credentials" both when trying to use my Google account to log in, and the account I attempted to create.

**Comment by Supamiu** [comment]
Can you please give me the email of the google account you used (you can PM me on discord if you don't want to paste it here).

The issue here is the fact that you tried to log-in first using google, which created an account entry, so when you tried to register using it, the account entry was existing but in a weird state where it exists with no data, resulting in an already used email but inexistant account.

What is strange is the fact that you couldn't register using email and password, I'm curious to see if this entry is registered and if front-end did shit or if the registration failed completly, having the email used for that could be nice too to check this.

Thank you for your report.

**Comment by RangePup** [comment]
The Google email I used was rangepup@gmail.com, and that was the same email
I tried to use to register.

On Feb 2, 2018 2:22 AM, "Flavien Normand" <notifications@github.com> wrote:

Can you please give me the email of the google account you used (you can PM
me on discord if you don't want to paste it here).

The issue here is the fact that you tried to log-in first using google,
which created an account entry, so when you tried to register using it, the
account entry was existing but in a weird state where it exists with no
data, resulting in an already used email but inexistant account.

What is strange is the fact that you couldn't register using email and
password, I'm curious to see if this entry is registered and if front-end
did shit or if the registration failed completly, having the email used for
that could be nice too to check this.

Thank you for your report.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Supamiu/ffxiv-teamcraft/issues/192#issuecomment-362517584>,
or mute the thread

**Comment by Supamiu** [comment]
Alright, you should now be able to register (don't try to login using your gmail account, register first).
