### ISSUE TITLE
style: better design for mobile

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#22]
At the moment, the application (looking at you, list page) is very ugly in mobile design, adding a responsive design for this kind of device would be a big plus.

**Comment by leofidus** [comment]
That would also solve some issues when using it on the desktop with a window less than 1920 pixels wide. For example the following happens when I open the Grade 3 Picture Frame recipe on my second screen:

![ffxivteamcraft](https://user-images.githubusercontent.com/4348296/31144248-6fcc6dee-a880-11e7-9740-d29735458e33.PNG)

(note the huge empty spaces combined with buttons overlapping because they ran out of space)

**Comment by Supamiu** [comment]
Kinda fixed, might reopen for future mobile support
