### ISSUE TITLE
bug: Aetheryte problems (missing some, wrong place on others)

### ISSUE THREAD

**Issue by AliciaJewel** [Supamiu/ffxiv-teamcraft#261]
In the Alarms section on the site, pulling up a node in Azys Lla reveals that its map has, in addition to the Helix Aetheryte, the Aetherytes for Idyllshire and Wineport.

**Comment by Supamiu** [comment]
This issue is also present for Idylshire afaik, not sure how this could be fixed but definetly needs to be logged as an issue.

Thank you for the report 👍

**Comment by mihawk90** [comment]
I assume you mean the hinterlands, not Idyllshire itself ;)

But since we had that topic a few days ago in the discord, I'll copy what Clorifex had to say about it:

> Miu
> that's an issue
> Because idylshire's aetheryte is considered as being in Hinterlands map
> Clorifex
> Only for the purposes of teleport cost calculation
> Real location will be if you follow the Aetheryte -> Map link

**Comment by mihawk90** [comment]
Another one:
![image](https://user-images.githubusercontent.com/556162/39673932-f06bb910-5144-11e8-91f1-181bfb6845e0.png)

**Comment by mihawk90** [comment]
![image](https://user-images.githubusercontent.com/556162/39675948-444c5aea-5162-11e8-9d59-34a082c27b43.png)

**Comment by mihawk90** [comment]
Central Thanalan - double Black Brush
![image](https://user-images.githubusercontent.com/556162/41825308-6914459e-781e-11e8-958a-20967bb1921f.png)

**Comment by mihawk90** [comment]
Mor Dhona:

https://cdn.discordapp.com/attachments/355098552122343424/460833653740797962/unknown.png

**Comment by ayyaruq** [comment]
Was looking into #558 but anyway, seems problems are due to duplicate ID data in `app/core/data/sources/aetherytes.ts`.

Count | Var
-- | --
2 | 'nameid': 1484
2 | 'nameid': 216
2 | 'nameid': 2300
2 | 'nameid': 337
3 | 'nameid': 2082
3 | 'nameid': 290
3 | 'nameid': 40

Not sure if this is relevant but there's a lot of duplicate placename IDs too. Each aetheryte should have a unique placename so no reason it would dupe that I can think of.

Count | Var
-- | --
2 | 'placenameid': 2001
2 |         'placenameid': 2002
2 |        'placenameid': 2082
   2 |        'placenameid': 2406
   2 |        'placenameid': 2407
   2 |        'placenameid': 2408
   2 |        'placenameid': 2409
   2 |        'placenameid': 2410
   2 |        'placenameid': 2411
   2 |        'placenameid': 32
   2 |        'placenameid': 33
   2 |        'placenameid': 43
   2 |        'placenameid': 45
   2 |        'placenameid': 46
   2 |        'placenameid': 52
   2 |        'placenameid': 56
   3 |        'placenameid': 2100
   3 |        'placenameid': 2101
   3 |        'placenameid': 2403
   3 |        'placenameid': 28
   4 |        'placenameid': 2300
   4 |        'placenameid': 29
   4 |        'placenameid': 40
   4 |        'placenameid': 53
   6 |        'placenameid': 2301
   8 |        'placenameid': 41
   9 |        'placenameid': 2404
  18 |        'placenameid': 1484

**Comment by Supamiu** [comment]
Fixed in 5.0 yay !
