### ISSUE TITLE
bug: alarms don't sync between multiple instances running

### ISSUE THREAD

**Issue by mihawk90** [Supamiu/ffxiv-teamcraft#275]
## I'm submitting a...
* (x) Bug report *- please add **bug:** before the title*
* (_) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

### Browser
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.170 Safari/537.36 Vivaldi/1.96.1111.3

Have you disabled script-/adblockers before submitting? yes

## Current behavior
When having multiple tabs of Teamcraft open, Alarms are not synced between multiple tabs, so you eventually may end up with something like this:
![image](https://user-images.githubusercontent.com/556162/37246902-86fced32-24b2-11e8-95f6-154f4286a26f.png)

I haven't tried this yet, but I suspect that whatever tab is closed last saves the alarms permanently.

## Expected behavior
Alarms should sync, just like item progress does.

## Steps to reproduce
1. Open a tab of teamcraft and add some Alarms (or don't, doesn't actually matter).
2. Open a second tab and add alarms
3. check the first tab, alarms are missing in first tab and never saved properly.

**Comment by Supamiu** [comment]
The solution might be to migrate alarms to database to be able to handle modifications in realtime, as localstorage is clearly the problem here

**Comment by mihawk90** [comment]
Theoretically you could also detect changes in LocalStorage and update other tabs automatically (see [here](https://stackoverflow.com/questions/4671852/how-to-bind-to-localstorage-change-event-using-jquery-for-all-browsers), though this is in jQuery it should be possible with vanillaJS even).

It might still be good to move alarms to database though if one is using a smartphone as a companion app or something though.

**Comment by Supamiu** [comment]
I thought a bit about this feature and saw a minor issue: time sync.

Let me explain this:

Whenever you come to a page with a timer or anything related to eorzean time, an instance of [EorzeanTimeService](https://github.com/Supamiu/ffxiv-teamcraft/blob/master/src/app/core/time/eorzean-time.service.ts) is created (and kept alive in case you need it elsewhere in the app, as it's using dependency injection. This means that the [ticker](https://github.com/Supamiu/ffxiv-teamcraft/blob/master/src/app/core/time/eorzean-time.service.ts#L14) for eorzean clock won't be synced, so you could easily have something like 3 tabs with same alarms but ticker not synced, I don't see how this could be fixed without greatly increasing database usage (would require 3 calls per second in a google cloud function, which means 259 200 calls per day, being 259 200 write operations per day too.

That being said, once the alarms will be registered to the database, you should only have one of the alarm sound ringing, but i'm not sure since the delay might be very short between two instances, probably shorter than the delay for changes to propagate between instances.
