### ISSUE TITLE
feat: read/write permissions management

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#277]
## I'm submitting a...
* (_) Bug report 
* (x) Feature request
* (_) Support request

## What feature are you proposing

Being able to manage read/write rights on lists could be nice, could be nice on workshops too.

## What is the use case for this feature?

A FC leader creates a workshop, he wants the other officers to be able to add/remove lists from it, same for lists inside it, having this available for lists would act exactly like this.

## Question/Discussion

Should list creators give permission to participate on a list? Given the fact that a list could be "trolled", aka resetting it, removing progression, or messing with amounts.

**Comment by IeYasuru** [comment]
A shared list can already be "trolled" by people, ticking stuff off that they haven't actually gathered or crafted as it is. But it would be super nice to be able to grant certain (registered) people the ability to add/remove lists to a shared Workshop for an FC instead of having to create and share many links between officers/crafters, or requiring talking to one person and waiting for them to do it, which can sometimes be awhile and make a project take even longer depending on how reliable that person is. 

Maybe keeping lists as read only for Anons, and granting write permissions (marking off items as gathered/crafted) while providing an audit log for the Workshop/List owner and those with permission to said log to see who is marking stuff off (and being able to go after them/remove them from the list if they are trolling) would be good. It would provide the workshop owner a lot of fluidity in how it's used by allowing others to manage it as well if necessary and keeping track of who is doing what so troublemakers can be removed.

**Comment by Supamiu** [comment]
I think there's 3 levels of permissions we need to consider:

 * R: Read, the ability to see the list, basically everyone is a reader
 * P: Participate, basically checking items, mark as working on it, comment
 * W: Write, add items to the list (or add items to the workshop if that's a workshop).

I think it's best to have everybody with R permission, and being able to add P and W permissions to users based on their account (you won't be able to edit permissions for anonymous users).

**Comment by IeYasuru** [comment]
Yeah, registered accounts would be required to set permissions for them. If there was a way to automatically grant members of the same FC P permission in an FC-tagged workshop, that could be useful. Otherwise, non fc-tagged workshops could be manually handled on their permissions, and W permission would still need to be granted by the workshop/list owner, fc-tagged or not.
