### ISSUE TITLE
feat: Import lists from other sites

### ISSUE THREAD

**Issue by SuperJugy** [Supamiu/ffxiv-teamcraft#311]
## Feature Request:
As a user I want to be able to import a list from other sites by the means of parsing URLs or encoded lists. I know that supporting lots of sites is not possible, but at least the most relevant. For example I know teamcraft uses garleand data as an API, so it would be nive to be able to parse garleand data crafting lists.

## What is the use case for this feature?
There are sites like garleand data that generate crafting list for example of the best gear for a certain class at certain level. But then we have to manually recreate this list in teamcraft which is a minor annoyance.

An example of a garleand data list URL:

https://www.garlandtools.org/db/#group/Crafting%20List{item/11886|item/11929|item/11959|item/11964|item/11969|item/11971|item/11977|item/11982|item/12018|item/12012|item/12015|item/12021+2}

Example of a ffxivcrafting list URL:
http://www.ffxivcrafting.com/list/saved/15538,1:15549,1:15515,1:15516,1:15534,1:15518,1:15519,1:15530,1:15531,1:15532,1:15533,2

As a side note, it would also by nice to export lists to garleand data, since garleand data can for example calculate set totals. although one normally would start from there rather than from here.

**Comment by Supamiu** [comment]
Hi, thank you for your feature request 😄 

This is a very hard thing to do since I need more than what's in the url to properly create a list, I need both itemId and recipeId, having just the recipe id is not enough unfortunately (at least for now).

I'll check what can be done to implement such a feature (like it has been done by xivdb, by xivdb since it adds the data I need).

Can you please elaborate on the "set totals" calculation? I think this already exists in Teamcraft

**Comment by SuperJugy** [comment]
Hi, in garlean data if you make a list of gear, it will make a sum of the stats and calculate the average item level. Obviously that is not the purpose of this tool. The export is not really needed too. As for the recipe id. I don't see need it. This is what I was thinking of:

1. have a dialog where you input the name of a new list and the paste the url.
2. I would then read if it is a valid garlean data url
3. Use substring and split to get the ids of the items and quantities from the url
4. Map the garlean data ids to teamcraft ids (assuming they are not the same) 
5. Create the new list with the correct name, ids and quantities.

I don't think that even an api call is needed for this. At least for garlean data.

**Comment by SuperJugy** [comment]
My understanding is that the url is not an id (like in teamcraft) but rather a big query with the item ids and quantities. That is why they are not persistent like in teamcraft except for the local copy saved in cookies. The url is meant to be shared with other people but each will have its own local copy.

**Comment by Supamiu** [comment]
The url of both garland and ffxivcrafting are the same kind of data, item ids and quantities. The issue is that I need recipe Id in order to create a list, because of recipes like ARM/BSM ingots where two recipes exist. I can still create a workaround to assume you're using the first one and that's it, only crystals change.

That being said, the item ids are exactly the same in both teamcraft and garland 😉 the only element I need that's not in the list url is recipe id, but I might be able to create a method to create a list without this id. Some investigation is needed ^^

**Comment by SuperJugy** [comment]
Ahh, gotcha. Makes sense

**Comment by SuperJugy** [comment]
So what happens when you add an item with multiple recipes currently? Do you list the item multiple times and let the user choose? What about items that use these items as a precraft? I would imagine you already do stuff like this somewhere else in the code.

I would love to contribute but I have only used typescript for front-end not backend. Not very familiar with this type of project.

**Comment by Supamiu** [comment]
If I'm only using the item Id and using the first recipe as addition to the list, then this import feature can almost be easy to do 😄
