### ISSUE TITLE
bug: creating shared items mark all materials as used if you only mark you have half materials.

### ISSUE THREAD

**Issue by namnomm** [Supamiu/ffxiv-teamcraft#330]
## I'm submitting a...
* (X) Bug report *

### Browser : Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0 

Have you disabled script-/adblockers before submitting?  Y

## Current behavior

In any list I create, if I have 2 recipes added to a list that uses the same items (ie. Flax) and for example I have only 8 of 10 flax farmed so far and I put that in the field that I have 8 of 10 flax. I then go and create one of the end products that uses flax and I have only 1 left (and need 2 more still to farm), it will say that the entire thing is 10/10 and farmed. It seems to be taking from the deficit instead of what's at hand.

## Expected behavior

Ideally I'd think if you check off you make an item that uses some (but not all) of the materials, it should be taking from what it says you have first instead of taking from the deficit and now saying that the materials are all farmed and accounted for.

## Steps to reproduce
1. Add 2 recipes to a list that use a same material.
2. In the list, say you have half of the farmed materials.
3. Checkmark you created 1 of the 2 recipes.
4. Notice that the materials are saying it is complete, even if you said you only had half.

**Comment by Supamiu** [comment]
This is an issue that I need to address in an UX way, let me explain:

When you create a list, you can say that you already have a given item X times, adding this amount will trigger a recursive function that will set the amount required * the amount of crafts for each ingredient. 

Example: 

 * I created a list with 10 iron ingots required as precraft.
 * As I already have 8 ingots in my inventory, I change the amount from 0 to 8 to reflect this.
 * `8*3`, so 24 Iron Ores are added to the current (0) Iron Ores amount. because now I only need 6 ores to craft my ingots.

This issue happens because if you do the reverse order (add materials and then mark as crafted), marking as crafted will add the materials too, that's why it reaches the maximum amount.

A simple fix would be to mark as used if the materials are here but not used for now, or add an option for crafts to be added without adding materials to the list, but this could result in a corrupted list with strange amounts just because of a small mistake.

**Comment by SuperJugy** [comment]
Not to sound pedantic and I know I've said a lot. but using the counting method if ffxivcrafting.com (which is already implemented and can be enabled in the settings) solves this issue nicely:

Same example:

- I created a list with 10 iron ingots required as precraft.
- As I already have 8 ingots in my inventory, I change the amount from 0 to 8 to reflect this.
- 8*3, so 24 Iron Ores are deleted from the amount of Iron Ores still needed. because now I only need 6 ores to craft my ingots.

In both cases anyway, if you have already added materials that you have, and then partially use them in a craft, there is no way for the system to know that since you crafted an ingot, it should delete 3 ores. this makes sense because you could have bought the ingot (since it is a precraft). But the nice thing about removing from the amount needed instead of adding to the amount that you have, is that it will match what you have in your inventory so it is easier to update the list in this case. if you set the ingots to 8 and now the system says you have the wrong amount of ores. you can simply check your inventory and set the amount of ores to what you see.

In any case, the easiest way to avoid this issue is not to precraft until you have all the mats, AND to first fill the amount of precrafts you have and THEN the amount of mats that you have.

**Comment by Supamiu** [comment]
Yeah that's what I want to implement, the idea is to increment the amount of items you have automatically only if you have already used all of what you have at the moment, meaning that you got some in another way. 

I think it shouldn't be up to the user to choose when to craft, if you have something like 1k ingots to craft (which happens with airships), you don't want to wait for all the mats to craft them, you want to begin the crafting process asap. That's why I'll try to change this system to take used mats into account 😄
