### ISSUE TITLE
bug:Characters with short names cannot be found

### ISSUE THREAD

**Issue by Cypher121** [Supamiu/ffxiv-teamcraft#392]
Bug report 

## Environment
Any

## Current behavior
If characters have names that don't find exclusively them on lodestone, they might not appear on the first search page for their own name. If that happens, TeamCraft cannot find them.

Example: "Dan Dan" on Ragnarok. Appears on the seventh page of results when searching on the lodestone

## Expected behavior
Should find the character

## Steps to reproduce
Open the Profile tab, edit character, try to find Dan Dan on Ragnarok

**Comment by Cypher121** [comment]
The problem seems to be coming from this request https://github.com/Supamiu/ffxiv-teamcraft/blob/e442cf9d7e23d74c43bd80e0f12882ba3a552338/src/app/core/api/data.service.ts#L195

XIVSync splits its data by pages as well, so if the "total" field in the response is longer than the result list and there is no character, a repeat request must be sent with "&page=2", "&page=3" and so on added

**Comment by Supamiu** [comment]
Hi, thank you for your bug report (and your investigation 👍 )

The issue is indeed quite complicated, as you noticed, xivdb uses paging and Teamcraft doesn't read all the pages.

Additionnaly, it's capped to 1k results afaik, so your character might not even be in the results (see https://xivsync.com/character/search?name=Dan%20Dan&server=Ragnarok).

I don't see a proper way to solve that for now, you can DM me your lodestoneID and email used for the account on discord and I'll setup the id by myself in the db.

**Comment by Cypher121** [comment]
Not my character, but I've told the owner to contact you.

An alternative solution would be to add an option to link character by ID/lodestone url directly
