### ISSUE TITLE
feat: Multiple Characters for Crafting

### ISSUE THREAD

**Issue by SamAkemi** [Supamiu/ffxiv-teamcraft#411]
I have 2 characters and both have 2 specialists.  At the moment I have to have 2 separate accounts and be able to run 2 copies of TC app which you are addressing, thankyou for that, but it would be great if the app could save the stats/profiles of each character so that we could just swap characters within the one instance of the app.

It would be a great support feature to add to the list when promoting the app too.

Thankyou Miu.

**Comment by Supamiu** [comment]
The hard part here is that I don't know how commission board should behave with multiple characters, do you have to select one manually? what to do when you want to apply for a commission?

Honestly, the more I think about this, the more I think it can't be done :/ even if I definitely see the benefits.

**Comment by ascobolonline** [comment]
I thought about that as well, but I think it could be possible, ofcourse I don't 100% how you solved the commission board in the backend right now.
But I thought of it along this line:
![commissionboard](https://user-images.githubusercontent.com/3620177/42312170-f978bc5e-803f-11e8-9c63-66a7f21c3349.PNG)
Means, you put the server selection above the board.. and the board not shows all possbile commission, but only for one server at a time. Why? I mean, if you are with a char on a server ingame, you want to see the commissions for that server only anyway, as you can't trade crafted items cross-server (yet). 
And if you have 2 characters on the same server, it doesn't matter, as you use the teamcraft account as "commission account" right? I mean, you just need to tell them from which char they get the commission result, within Teamcraft i would use the teamcraft account. (You could add an account image to the teamcraft profile instead of using the small ingame char image.)
 And the possible servers in the dropdown on the top (that white rectangle ;-)) comes from the servers of your added chars in teamcrafts profile.

Regarding the profile you could go this way:
![profiles](https://user-images.githubusercontent.com/3620177/42312359-6a469104-8040-11e8-86e8-24b0feaaa68d.PNG)
Means, put the patreon settings on top as these are independent of the ingame chars. below you have a list of chars, similar to workshops.. so you can unfold a char and see its classes etc and then fold it again..
and on the bottom you have the contact list.

No idea if it is doable this way, but just from the UI/UX part, it should be possible. No idea though, if it fits to the coding backend. :-)
