### ISSUE TITLE
Bug: Inconsistent Progress and Totals With Recipes With Yields Of More Than One

### ISSUE THREAD

**Issue by Norinara** [Supamiu/ffxiv-teamcraft#44]
Couldn't think of a better way to title that.
The total required mats for the specified end product is correct based on the yields. However when crafting an Infusion of Strength for example, one craft yields 3 potions, it should have used 1 Crescent Spring Water but it instead thinks 3 was used. The result is that with a goal of making 99 potions, the website will say all materials have been used after 33 potions have been made. After 33 strength potions 22 Parsley should have been used instead of 66, 11 spring water, and 11 salt crystal.

<img width="538" alt="capture" src="https://user-images.githubusercontent.com/32250740/30837653-19e410b2-a22c-11e7-9c61-981571fbd0de.PNG">

<img width="540" alt="capture 2" src="https://user-images.githubusercontent.com/32250740/30838354-afe80ede-a230-11e7-9267-d3e36549d834.PNG">

**Comment by Supamiu** [comment]
This is clearly a consistence problem, the main question behind that is "Do we want to show the number of *items* to do in the Items category or do we want to show the number of *crafts* to do?"

Actually, the application is doing both, which is bad ^^

I'll fix this asap, thanks for reporting the issue.

**Comment by Supamiu** [comment]
After thinking a bit about that, I think it would be better if we were just showing the number of crafts to do, not the number of items, because that's how every other section works and this behavior is generic.

I'll add a new feature to upgrade lists, which will destroy and recreate the list with the latest version of the application, because your list will no longer require 99 items but it sill require 33 crafts, which is the same but not in terms of display (technically you shouldn't be able to say "I made 14 potions" if the craft yields 3 items).
