### ISSUE TITLE
feat: private commissions

### ISSUE THREAD

**Issue by AcidAshe** [Supamiu/ffxiv-teamcraft#480]
## I'm submitting a...
* (_) Bug report *- please add **bug:** before the title*
* (x) Feature request *- please add **feat:** before the title*
* (_) Support request *- please come on [our discord](https://discord.gg/r6qxt6P) instead*

## What feature are you proposing

Private commissions!

## What is the use case for this feature?

Many crafters have repeat customers that exclusively order from them. It would be a neat thing to have private commissions tied into TC.
Maybe a flow like this:

1: The client and crafter add each other's userIDs to have mutual contact. This would trigger the ability to sign them onto a commission, mayhaps? The trigger being that both have each other added mutually, to avoid random requests from random people. Mayhaps also a setting in the settings tab to toggle accepting private commissions, so that crafters can overall opt out of being able to be privately commissioned?
2: Client makes a list to create a commission from, as normal, but there is an option to toggle private commission, which would then in turn bring up a drop-down or something with a list of mutual contacts to assign the commission to?
3: The crafter is notified of the commission, maybe yet another tab on the commission board? They can then chat with the client to negotiate price and such.
4: The crafter is given the option to accept or decline the request? (Mayhaps in future even forward the request to another crafter, who is a mutual contact of theirs? I often will pass orders to fellow crafters that I know, in cases with specialist locks.)
5: Commission then continues like a normal commission.

Please feel free to pick my brain on anything that isn't quite clear!

**Comment by MDlumia** [comment]
this honestly seems like a pretty decent idea.  i know i could get use from this for having people  being able to make requests to me  or orders to me directly from there browsers or such. it be easier to keep track things all inside TC which a decent amount of crafters use extensively. instead of needing to use TC and Discord and who knows what other  platforms.  it could even cover the needs of the private request feature  i mentioned in discord with out taking away from commission systems shine as i thought you were worried bout.

**Comment by AcidAshe** [comment]
the open commission board is still very useful for new people to easily just go "hey i need this who can help?" so i doubt it will lose use (once it actually GETS more use)
