### ISSUE TITLE
Modal Missing Close Action

### ISSUE THREAD

**Issue by Trevor-Welch** [Supamiu/ffxiv-teamcraft#54]
![image](https://user-images.githubusercontent.com/22405085/31155006-1eccb8b0-a879-11e7-8cdf-5794b57aba76.png)

No way to cancel registration at all unless you refresh page or successfully enter correct details into the modal.

Need to add simple modal closing functionality.

**Comment by Trevor-Welch** [comment]
Update: Even refreshing will no let you continue, it actually traps you until you register.

**Comment by Supamiu** [comment]
This is the intended behavior, the goal is to avoid having a user that has an account on the website with no character associated to it. Because the account is actually used to filter recipes to find what you can do by yourself using your lodestone profile to get the lvl of each of your crafting jobs.
