### ISSUE TITLE
bug: completion state not saved in large lists (85 items)

### ISSUE THREAD

**Issue by phenaeri** [Supamiu/ffxiv-teamcraft#557]
Chrome version 67.0.3396.99

Have you disabled script-/adblockers before submitting?
Yes, closed all Adblockers
### Teamcraft Link
https://ffxivteamcraft.com/list/RuglPMAa9SzROnWDFMVE

## Current behavior
Clicking "Completion" button (checkmark button) next to Adamantite Ore under Times Nodes section does not complete the item.  Adding custom amounts of completion does not save on refresh.
The above is occurring with Titanium Ore under Gatherings section.
The above is also occuring with Hardsilver Ore under Tomes/Tokens/Scripts section.
My particular list has about 85 items on it.

## Expected behavior
When completion button is clicked or added amounts are added to List Items, it should save the state.

## Steps to reproduce
1. Create list. 
2. Populate list with various items requiring gathering of Ore and Ore as a rewuirement for completed items.
3. Click completion button next to Ore.

**Comment by Supamiu** [comment]
Hello, thanks for your report 👍 

The bug is indeed from the fact that your list is very large, so it seems to take too much time to save it, resulting in the list not being saved at all upon modifications.

You can see that it's the case by trying on a smaller list: https://ffxivteamcraft.com/list/weOq8TEYRiYccPR5SZ8Z.

I'm currently working on 5.0 that will fix this kind of bad state management design issues, see #468 .

**Comment by phenaeri** [comment]
Sounds good.  Thank you very much for the wonderful tool.  I'll try to keep my lists to a reasonable size til then.

**Comment by Supamiu** [comment]
Closed by #576
