### ISSUE TITLE
Bug: Lists and more

### ISSUE THREAD

**Issue by Zancerc** [Supamiu/ffxiv-teamcraft#567]
Since today i can't delete my lists. Its still showing. Also if i start a list - i can't click any button like that i already have that item.

I tryed it with a new list put any item in it. In this case with Stewed River Bream x6 and i got that issue.
Resset progression or recreate list with latest update didn't help.

Chrome Version: Version 69.0.3497.81

It worked the last days perfect also with that patch number 4.4.4 so i don't know what was changed there.
![unbenannt](https://user-images.githubusercontent.com/40495336/45141442-2e139680-b1b6-11e8-9c75-013dc68f4984.jpg)

**Comment by Supamiu** [comment]
Hello, thanks for the report.

This issue is due to the fact that xivsync, the website I'm using for character data requests, currently has an issue with their certificate, making the website unavailable for Teamcraft.

This causes items to be readonly because Teamcraft can't check that you're the owner of the list based on your character.

I'm doing my best to tell ZAM (the owner of xivsync) to update the certificate, as it's a simple button press iirc. 

Sorry for the inconvenience, I'll close this issue once the certificate will be updated, fixing the issue you're facing.
