### ISSUE TITLE
[5.0] Levequest generation

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#595]
It could be nice to be able to generate lists from a levequest search system, similar to ffxivcrafting.

The idea is to have a page to search leves, and then be able to create a list for a given leve, with the amount of times I want to do it. Would add the corresponding items to a list.

**Comment by mattantonelli** [comment]
### 1. Search for the leve(s) by name and retrieve Leve content IDs

* DoH jobs are ClassJobCategory IDs 9-16 (CRP-CUL) [available in content endpoint]
* DoH leves have LeveAssignmentType ID 5-12 (CRP-CUL) [available in search endpoint - topmost level]

`https://xivapi.com/search?indexes=leve&string=got&filters=LeveAssignmentType.ID>=5,LeveAssignmentType.ID<=12&columns=ID`
```json
{
    "ID": 201
}
```

Columns for additional filtering:

* **ClassJobCategory.Name:** Job name (CRP, WVR, etc)
* **ClassJobLevel:** Level requirement

*Note: Consider how translations will be handled in the future. If TC is set to another language, will this language be set automatically when searching XIVAPI, or should a different search column be used?*

### 2. Query Leve data by ID and retrieve CraftLeve content IDs

`http://xivapi.com/Leve?ids=201,494,248,330,1281,231,413,242,26,25,207&columns=DataId`

```json
{
    "DataId": 917656
}
```

### 3. Query CraftLeve data by ID and retrieve all necessary data

`http://xivapi.com/CraftLeve?ids=917656,917657,917757,917763,917769,917780,917900,917814,917843,917978,918338&columns=Item0TargetID,ItemCount0,Repeats,Leve.Name,Leve.GilReward,Leve.ExpReward,Leve.LeveVfx.Icon,Leve.LeveVfxFrame.Icon,Leve.LeveAssignmentType.Icon,Leve.ClassJobLevel`

```json
{
    "Item0TargetID": 2219,
    "ItemCount0": 1,
    "Leve": {
        "ClassJobLevel": 1,
        "ExpReward": 1770,
        "GilReward": 94,
        "LeveAssignmentType": {
            "Icon": "/i/062000/062502.png"
        },
        "LeveVfx": {
            "Icon": "/i/080000/080033.png"
        },
        "LeveVfxFrame": {
            "Icon": "/i/080000/080005.png"
        },
        "Name": "Got Your Back"
    },
    "Repeats": 0
}
```

* **Item0TargetID:** ID of item required for turn-in
* **ItemCount0:** Quantity of item required for turn-in
* **Repeats:** Number of times the levequest can be repeated. 0 = None, 2 = Triple turn-in
* **Leve:**
  * **Name:** Name of the levequest
  * **GilReward:** Gil reward
  * **ExpReward:** EXP reward
  * **LeveVfx.Icon:** Leve card image
  * **LeveVfxFrame.Icon:** Leve card frame image
  * **LeveAssignmentType.Icon:** Job requirement image
  * **ClassJobLevel:** Level requirement

Notes:

* HQ turn-ins grant 2x exp and gil, but this is the same for all leves.
* Some crafting leves offer the ability to do triple turn-ins. These should be indicated.
  * But should there be an option for this in order to always do 3x the mats?
* Item name can be retrieved using the pipe service: `itemId | itemName | i18n`
