### ISSUE TITLE
feat: Support for korean accounts

### ISSUE THREAD

**Issue by Supamiu** [Supamiu/ffxiv-teamcraft#639]
Korean players need some specific systems integrated in Teamcraft, and some limitations, here is the list of what we need to implement to properly support korean players:

- [x] Create an account without lodestoneId, just a character name.
- [x] Disable some features when user account is flagged as korean:
  - Free company permissions
  - Marketboard informations
- [x] Support for korean item names (related to xivapi)

**Comment by viion** [comment]
It is very easy for me to add Korean (and Chinese if you want it) to XIVAPI. This would be all string data for the official client. Exclusive Korean and Chinese items are a bit more complicated due to their structure being out of sync with our client (so I can't really run it through the same process right now).

Definitely do able, just need time to do it.

**Comment by Supamiu** [comment]
Closed by #785
