### ISSUE TITLE
bug: Koshu Pork flagged as possible HQ ingredient for Shakshouka recipe

### ISSUE THREAD

**Issue by leewdch** [Supamiu/ffxiv-teamcraft#740]
**Describe the bug**
When I open the configuration window [Koshu Pork](https://ffxiv.gamerescape.com/wiki/Koshu_Pork) is in the list for the possible HQ ingredients even if it's only available in NQ in game.

**Screenshots**
![image](https://user-images.githubusercontent.com/11262717/51918084-29f44980-23e1-11e9-9b4a-10b7d96bc8c7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 71.0.3578.98 (Official Build) (64-bit)

**Additional context**
You can obtain Koshu Pork only with Yellow Crafters' Scrips or from the marketboard. In both cases only NQ items are currently available in game.

**Comment by Supamiu** [comment]
This is an issue that I'm afraid I might not be able to solve, I could add a flag by hand to say that this exact item can't be HQ, but the thing is that inside FFXIV data files, Kokshu Pork is marked as CanBeHq, meaning that they could add an HQ version of it later on, or maybe not, but the game says that it can be HQ.

So the only fix I see is to maintain a list of items that are flagged as HQ but cannot be, which seems meh because the list will have to evolve quickly :/

I understand the issue tho, if you prepare a rotation assuming all HQ and you see later on that this cannot be HQ, it's frustrating. But I'm not sure I can fix it properly without having to revert the fix later on.
