### ISSUE TITLE
bug: rollback on my account

### ISSUE THREAD

**Issue by rgdoabc** [Supamiu/ffxiv-teamcraft#786]
I just made a list and put it in my Workshop.
After updating and left the tab open for almost a hour, I tried to share it with my friend, but then everything went way back in time.

My workshop was empty and in my lists there was only a old one, that was already deleted.

EDIT: after some tests, it seems to happens only when I share a list.

**Comment by Supamiu** [comment]
Hello, thank you for your report.

I'm going to need more details about this bug, especially regarding steps to reproduce.

I expect this to come from a very large list created or something else happening, but I couldn't reproduce it by just reading your issue. I could use your user ID too (it's not an issue if you share it, you can find it inside settings page).

**Comment by rgdoabc** [comment]
UserID: K5GQYBSBwkUVxvECDhcaK6VD6N33

Yes, the list is quite big.

What I did:

1. I created it; 
2. put the items that I already had in;
3. went to collect a few more;
4. put it in the list;
5. left the tab open for a while;
6. refresh the page to see if everything was right. It was;
7. closed the tab;

Went back later and only half of the things that I added in step 2 was there.

**Comment by Supamiu** [comment]
Ok, if the list is quite big, I think the issue is the same as a lot of other big lists issues: database.

I'm saying that because firestore, the realtime database system used for Teamcraft, is limited to 1MB documents and doesn't recommend writing big chunks of data too often, because it might cause data loss.

A big list (100+ items) average size is 300kB, this means that it's already pretty big for firestore, and might cause some data loss when saving data.

Unfortunately there's not a lot of things I can do for it, I'm thinking about having an offline lists feature for very large lists but you wouldn't be able to share it so it's meh.

Big lists will be an issue for the next updates for sure, there's some options I'm trying to consider to reduce data size but 5.0 already managed to support 50+ items lists easily, now we have to break the 100 items limit.

I would advice to create smaller lists to make sure they are reliable, and use workshops to share them to your friends all at once.

**Comment by rgdoabc** [comment]
Thanks, I'll try to break the list.
